export const servicesData = [
  {
    slug: "general-dentistry",
    title: "General Dentistry",
    subtitle: "For the Entire Family",
    shortDesc: "Comprehensive dental care for patients of all ages, from routine checkups to preventive treatments.",
    fullDesc: `Our general dentistry department is the foundation of everything we do at AP Dental. We believe that preventive care is the key to a lifetime of healthy smiles. Our board-certified dentists provide thorough examinations, professional cleanings, digital X-rays, and personalized oral health education for every member of your family.\n\nWhether you need a simple filling, a root canal, or guidance on proper brushing techniques, our team ensures every visit is comfortable, thorough, and tailored to your unique needs. We use the latest diagnostic tools to catch issues early, saving you time, discomfort, and cost in the long run.`,
    image: "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=1200&q=80",
    features: ["Exams, Cleanings & X-Rays", "Crowns & Fillings", "Extractions", "All General Procedures"],
    icon: "/icons/cleaning.svg",
    priceNote: "Starting from TZS 50,000",
  },
  {
    slug: "orthodontics",
    title: "Orthodontics",
    subtitle: "Align Your Smile",
    shortDesc: "Straighten your teeth and correct your bite with modern braces and clear aligners.",
    fullDesc: `A straight smile is not just about aesthetics — it is about health. Misaligned teeth can lead to uneven wear, jaw pain, and difficulty cleaning. At AP Dental, our orthodontic specialists use cutting-edge digital planning to design treatment plans that fit your lifestyle and budget.\n\nFrom traditional metal braces to virtually invisible Invisalign aligners, we offer solutions for teens and adults alike. Every treatment begins with a free consultation and a 3D digital scan, so you can see your projected results before committing.`,
    image: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=1200&q=80",
    features: ["Invisalign & Braces", "Phase I & II Treatments", "All-Digital Planning", "Free Consultation"],
    icon: "/icons/braces.svg",
    priceNote: "Consultation free",
  },
  {
    slug: "childrens-dentistry",
    title: "Children's Dentistry",
    subtitle: "Gentle & Fun",
    shortDesc: "Kid-friendly dental care in a warm, welcoming environment that makes visits fun, not scary.",
    fullDesc: `We know that early dental experiences shape a lifetime of oral health habits. That is why our pediatric dentistry team goes above and beyond to create a fun, stress-free environment for your little ones.\n\nOur certified pediatric dentists specialize in treating infants, children, and teens with patience, compassion, and age-appropriate techniques. From first tooth checkups to orthodontic evaluations, we help children feel safe and excited about taking care of their smiles. Sedation options are available for children with dental anxiety.`,
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1200&q=80",
    features: ["Certified Pediatric Dentists", "Kid-Friendly Environment", "Sedation Options", "Orthodontics"],
    icon: "/icons/replace.svg",
    priceNote: "Children under 5 get free first visit",
  },
  {
    slug: "cosmetic-dentistry",
    title: "Cosmetic Dentistry",
    subtitle: "Your Best Smile",
    shortDesc: "Transform your smile with whitening, veneers, bonding, and complete smile makeovers.",
    fullDesc: `Your smile is one of your most powerful assets. Our cosmetic dentistry team combines artistry with advanced dental technology to create natural-looking, stunning results.\n\nWhether you want a subtle brightening or a complete smile transformation, we offer a full range of cosmetic treatments including professional teeth whitening, porcelain veneers, dental bonding, gum contouring, and full smile makeovers. Every cosmetic plan is fully customized to complement your facial features, skin tone, and personal goals.`,
    image: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=1200&q=80",
    features: ["Teeth Whitening", "Veneers & Bonding", "Smile Makeovers", "Gum Contouring"],
    icon: "/icons/beforeafter.svg",
    priceNote: "Custom quotes available",
  },
  {
    slug: "oral-surgery",
    title: "Oral Surgery",
    subtitle: "Specialty Services",
    shortDesc: "Expert surgical care including wisdom teeth removal, implants, and complex extractions.",
    fullDesc: `When dental issues require surgical intervention, you need a team you can trust. Our oral surgery department is led by experienced specialists who perform everything from routine extractions to complex implant procedures.\n\nWe utilize 3D imaging and computer-guided surgical planning to ensure precision and safety. Our modern surgical suites are equipped with hospital-grade sterilization and sedation options to keep you comfortable throughout your procedure. From wisdom teeth removal to full-mouth dental implants, we are here to restore your oral health.`,
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=1200&q=80",
    features: ["Wisdom Teeth Removal", "Implants", "Endodontics (Root Canals)", "Dentures"],
    icon: "/icons/implant.svg",
    priceNote: "Surgical consult required",
  },
  {
    slug: "emergency-care",
    title: "Emergency Care",
    subtitle: "We're Here When You Need Us",
    shortDesc: "Same-day appointments for dental emergencies. Walk-ins welcome. 24/7 phone support.",
    fullDesc: `Dental emergencies do not wait for convenient times, and neither do we. AP Dental offers same-day emergency appointments and walk-in availability at both our Msasani and Upanga locations.\n\nWhether you are dealing with severe tooth pain, a broken tooth, a lost filling, or a dental infection, our emergency team is ready to provide rapid relief and lasting solutions. We have dedicated emergency slots every day, and our 24/7 phone line ensures you can always reach a dental professional when you need one most.`,
    image: "https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?w=1200&q=80",
    features: ["Same-Day Appointments", "Walk-Ins Welcome", "Pain Management", "24/7 Phone Support"],
    icon: "/icons/rootcanal.svg",
    priceNote: "Emergency fees may apply",
  },
];

export const galleryImages = [
  { url: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=1200&q=80", title: "Welcoming Reception", desc: "A warm, comfortable space designed to put you at ease the moment you walk in.", category: "Facility" },
  { url: "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?w=1200&q=80", title: "State-of-the-Art Surgery", desc: "Equipped with the latest ergonomic dental chairs and highly sterile surgical fields.", category: "Technology" },
  { url: "https://images.unsplash.com/photo-1579684389782-64d84b5e901a?w=1200&q=80", title: "Advanced 3D Imaging", desc: "Low-radiation digital X-rays and 3D intraoral scanners for ultra-precise diagnostics.", category: "Technology" },
  { url: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=1200&q=80", title: "Sterilization Lab", desc: "Our hospital-grade autoclaves and multi-stage sterilization protocols ensure absolute safety.", category: "Facility" },
  { url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&q=80", title: "Comfort Waiting Lounge", desc: "Enjoy complimentary refreshments, high-speed Wi-Fi, and a soothing ambient environment.", category: "Facility" },
  { url: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=1200&q=80", title: "Premium Dental Suites", desc: "Where expert treatment meets patient-first care and advanced cosmetic procedures.", category: "Facility" },
  { url: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1200&q=80", title: "Pediatric Play Area", desc: "A fun, colorful space designed to help children feel relaxed and happy before their appointment.", category: "Facility" },
  { url: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=1200&q=80", title: "Our Dental Team", desc: "Meet our board-certified dentists and friendly support staff dedicated to your care.", category: "Team" },
];

export const teamMembers = [
  {
    name: "Dr. Adrian Popa",
    role: "Founder & Lead Dentist",
    bio: "With over 15 years of experience in general and cosmetic dentistry, Dr. Popa founded AP Dental with a vision to make world-class dental care accessible to every family in Dar es Salaam.",
    image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=600&q=80",
  },
  {
    name: "Dr. Fatima Hassan",
    role: "Orthodontic Specialist",
    bio: "Dr. Hassan is a board-certified orthodontist specializing in Invisalign and traditional braces for teens and adults. She brings precision and artistry to every smile transformation.",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&q=80",
  },
  {
    name: "Dr. James Mwamba",
    role: "Oral Surgeon",
    bio: "A skilled oral and maxillofacial surgeon, Dr. Mwamba handles complex extractions, implant placements, and emergency surgical cases with calm expertise.",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=600&q=80",
  },
  {
    name: "Dr. Amina Juma",
    role: "Pediatric Dentist",
    bio: "Dr. Juma has a gift for making children feel at ease. Her gentle approach and kid-friendly techniques have made her one of the most trusted pediatric dentists in the city.",
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=600&q=80",
  },
];
